## *Задание на повторение материала урока 1 + 2

#### 1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [85]:
import numpy as np
a = np.linspace (12,23,12)
display(a)

array([12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.])

#### 2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [98]:
a_1 = a.reshape(1,12)
a_2 = a.reshape(2,6)
a_3 = a.reshape(3,4)
a_4 = a.reshape(4,3)
a_5 = a.reshape(6,2)

[[12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23.]]


#### 3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [93]:
a_1 = a.reshape(-1,3)
a_2 = a.reshape(-1,4)
a_3 = a.reshape(3,-1)
a_4 = a.reshape(2,-1)
a_5 = a.reshape(6,-1)

[12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23.]
[[12. 13. 14.]
 [15. 16. 17.]
 [18. 19. 20.]
 [21. 22. 23.]]
[[12. 13.]
 [14. 15.]
 [16. 17.]
 [18. 19.]
 [20. 21.]
 [22. 23.]]


#### 4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [ ]:
#Нет, так как он содержит в себе одномерный массив (список из 12 значений). Поэтому является двумерным

#### 5. Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [101]:
rand_normal  = np.random.normal(0, 1, size=(3, 4))
print(rand_normal)
b=rand_normal.flatten()
print(b)

[[ 1.47846616  1.41550328  0.2374453  -1.77548219]
 [-2.19029637 -0.6294058   0.88026218  0.44015665]
 [ 0.0742865  -1.38323786  0.27172601  0.22665443]]
[ 1.47846616  1.41550328  0.2374453  -1.77548219 -2.19029637 -0.6294058
  0.88026218  0.44015665  0.0742865  -1.38323786  0.27172601  0.22665443]


#### 6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [13]:
a = -1* np.arange(-20,0,2)
print(a)

[20 18 16 14 12 10  8  6  4  2]


#### 7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [15]:
b = a.reshape(1,10)
print(b)
#Разница в том, что a содержит 10 значений, а b - только одно: список из 10 значений

[[20 18 16 14 12 10  8  6  4  2]]


#### 8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [32]:
a = np.zeros(6).reshape(2,3)
b = np.ones(9).reshape(3,3)
#print(a)
#print(b)
v = np.vstack((a,b))
print(v)

[[0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


#### 9. Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [105]:
a = np.arange(0,12).reshape(4,3)
at = a.transpose()
b = a @ at
print(b)
#inverse_b = np.linalg.inv(b) 
#print(inverse_b)
#Размер матрицы B - 4*4, так как матрица (4*3) умножилась на матрицу (3*4)
#Обратной матрицы у B нет, так как строки зависимы

[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]


#### 10. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [106]:
import random
random.seed(42)

#### 11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [107]:
random.seed(42) 
c = np.random.randint(0, 17, 16)
print(c)

[ 0 15 15 15  3 10 10  4  0 11 14 12 14 14  7 11]


#### 12. Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [111]:
matrix_c = c.reshape(4,4)
print('Матрица C:')
print(matrix_c)
matrix_d = b + matrix_c * 10
print('Матрица D:')
print(matrix_d)
det_d = np.linalg.det(matrix_d)
print('Определитель матрицы:')
print(det_d)
rank_d = np.linalg.matrix_rank(matrix_d)
print('Ранк матрицы:')
print(rank_d)
inverse_d = np.linalg.inv(matrix_d)
print('Обратная матрица:')
print(inverse_d)

Матрица C:
[[ 0 15 15 15]
 [ 3 10 10  4]
 [ 0 11 14 12]
 [14 14  7 11]]
Матрица D:
[[  5 164 173 182]
 [ 44 150 186 162]
 [ 23 196 289 332]
 [172 262 282 412]]
Определитель матрицы:
-146230599.9999997
Ранк матрицы:
4
Обратная матрица:
[[-0.01137587  0.01046142 -0.00380399  0.00397714]
 [ 0.02035402 -0.0034224  -0.01179794  0.00186144]
 [-0.0163089   0.01874423  0.00618215 -0.00514762]
 [ 0.00296846 -0.0150208   0.00485917  0.00310646]]


#### 13. Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

array([[False,  True, False,  True],
       [ True, False, False,  True],
       [False,  True,  True, False],
       [ True, False,  True,  True]])